services:
  fitx-booker:
    build: .
    environment:
      - FITX_USERNAME=${FITX_USERNAME}
      - FITX_PASSWORD=${FITX_PASSWORD}
      - FITX_STUDIO_ID=${FITX_STUDIO_ID}
      - FITX_COURSE_NAME=${FITX_COURSE_NAME:-functional x}
      - RUN_TEST=${RUN_TEST:-false}
